import {
  Supplier,
  SupplierSite,
  Material,
  Product,
  BOMItem,
  Plant,
  ProductionLine,
  Warehouse,
  Customer,
  Carrier,
  Route,
  PurchaseOrder,
  PurchaseOrderLine,
  InventoryItem,
  ProductionOrder,
  CustomerOrder,
  SupplyChainEvent,
  SupplierContract,
  SupplierPerformance,
  ScenarioDefinition,
} from '../src/types/index.js';

export class DigitalTwinRepository {
  public suppliers: Map<string, Supplier> = new Map();
  public supplierSites: Map<string, SupplierSite> = new Map();
  public materials: Map<string, Material> = new Map();
  public products: Map<string, Product> = new Map();
  public boms: BOMItem[] = [];
  public plants: Map<string, Plant> = new Map();
  public productionLines: Map<string, ProductionLine> = new Map();
  public warehouses: Map<string, Warehouse> = new Map();
  public customers: Map<string, Customer> = new Map();
  public carriers: Map<string, Carrier> = new Map();
  public routes: Map<string, Route> = new Map();
  public purchaseOrders: Map<string, PurchaseOrder> = new Map();
  public purchaseOrderLines: PurchaseOrderLine[] = [];
  public inventory: InventoryItem[] = [];
  public productionOrders: Map<string, ProductionOrder> = new Map();
  public customerOrders: Map<string, CustomerOrder> = new Map();
  public events: Map<string, SupplyChainEvent> = new Map();
  public contracts: Map<string, SupplierContract> = new Map();
  public performances: Map<string, SupplierPerformance> = new Map();
  public scenarios: ScenarioDefinition[] = [];

  constructor() {
    this.seedGoldenDataset();
  }

  private seedGoldenDataset() {
    // 1. SUPPLIERS
    const supplierData: Supplier[] = [
      {
        supplier_id: 'SUP-042',
        supplier_name: 'Apex Micro-Foundry & Optics',
        country: 'Taiwan',
        region: 'APAC',
        city: 'Hsinchu Science Park',
        supplier_type: 'TIER_1_SEMICONDUCTOR',
        risk_score: 84, // High risk due to cleanroom disruption
        capacity_score: 92,
        quality_score: 96,
        financial_score: 88,
        lead_time_days: 28,
        annual_spend: 18450000,
        active_flag: true,
        latitude: 24.782,
        longitude: 121.006,
      },
      {
        supplier_id: 'SUP-118',
        supplier_name: 'Kyoto Precision Semiconductor',
        country: 'Japan',
        region: 'APAC',
        city: 'Kyoto',
        supplier_type: 'TIER_2_QUALIFIED_ALTERNATE',
        risk_score: 16,
        capacity_score: 89,
        quality_score: 98,
        financial_score: 94,
        lead_time_days: 7, // Rapid secondary delivery
        annual_spend: 6200000,
        active_flag: true,
        latitude: 35.0116,
        longitude: 135.768,
      },
      {
        supplier_id: 'SUP-015',
        supplier_name: 'Bavaria Special Alloys & Castings',
        country: 'Germany',
        region: 'EMEA',
        city: 'Munich',
        supplier_type: 'TIER_1_METALLURGY',
        risk_score: 22,
        capacity_score: 95,
        quality_score: 97,
        financial_score: 91,
        lead_time_days: 14,
        annual_spend: 12800000,
        active_flag: true,
        latitude: 48.1351,
        longitude: 11.582,
      },
      {
        supplier_id: 'SUP-089',
        supplier_name: 'Valencian Advanced Optics SL',
        country: 'Spain',
        region: 'EMEA',
        city: 'Valencia',
        supplier_type: 'TIER_1_OPTICS',
        risk_score: 29,
        capacity_score: 84,
        quality_score: 93,
        financial_score: 82,
        lead_time_days: 18,
        annual_spend: 5400000,
        active_flag: true,
        latitude: 39.4699,
        longitude: -0.3763,
      },
      {
        supplier_id: 'SUP-201',
        supplier_name: 'Daegu Precision Actuators Ltd',
        country: 'South Korea',
        region: 'APAC',
        city: 'Daegu',
        supplier_type: 'TIER_1_MECHATRONICS',
        risk_score: 34,
        capacity_score: 90,
        quality_score: 94,
        financial_score: 87,
        lead_time_days: 21,
        annual_spend: 9100000,
        active_flag: true,
        latitude: 35.8714,
        longitude: 128.6014,
      },
      {
        supplier_id: 'SUP-007',
        supplier_name: 'Nordic Composite Fiber AB',
        country: 'Sweden',
        region: 'EMEA',
        city: 'Gothenburg',
        supplier_type: 'TIER_2_COMPOSITES',
        risk_score: 18,
        capacity_score: 88,
        quality_score: 96,
        financial_score: 93,
        lead_time_days: 12,
        annual_spend: 4800000,
        active_flag: true,
        latitude: 57.7089,
        longitude: 11.9746,
      },
      {
        supplier_id: 'SUP-055',
        supplier_name: 'Detroit Industrial Fasteners Co',
        country: 'USA',
        region: 'AMER',
        city: 'Detroit',
        supplier_type: 'TIER_2_HARDWARE',
        risk_score: 19,
        capacity_score: 96,
        quality_score: 95,
        financial_score: 90,
        lead_time_days: 5,
        annual_spend: 3200000,
        active_flag: true,
        latitude: 42.3314,
        longitude: -83.0458,
      },
    ];
    supplierData.forEach((s) => this.suppliers.set(s.supplier_id, s));

    // 2. MATERIALS
    const materialData: Material[] = [
      {
        material_id: 'MAT-1007',
        material_name: 'Precision Silicon Sensor Substrate (8-inch GaN-ready)',
        material_category: 'SEMICONDUCTORS',
        material_type: 'RAW_MATERIAL',
        unit_cost: 420,
        unit_of_measure: 'WAFER',
        criticality: 'CRITICAL',
        lead_time_days: 28,
        safety_stock: 600,
        minimum_order_qty: 250,
        primary_supplier_id: 'SUP-042',
        alternate_supplier_id: 'SUP-118',
        available_inventory: 936,
        reserved_inventory: 820,
        daily_consumption_rate: 180, // 936 / 180 = 5.2 days coverage!
      },
      {
        material_id: 'MAT-1012',
        material_name: 'Gallium-Nitride (GaN) Power Switching Die',
        material_category: 'POWER_ELECTRONICS',
        material_type: 'RAW_MATERIAL',
        unit_cost: 680,
        unit_of_measure: 'UNIT',
        criticality: 'CRITICAL',
        lead_time_days: 26,
        safety_stock: 350,
        minimum_order_qty: 150,
        primary_supplier_id: 'SUP-042',
        alternate_supplier_id: 'SUP-118',
        available_inventory: 494,
        reserved_inventory: 410,
        daily_consumption_rate: 95, // 494 / 95 = 5.2 days coverage!
      },
      {
        material_id: 'MAT-2041',
        material_name: 'Aero-Grade Titanium Alloy Rods Ti-6Al-4V',
        material_category: 'METALLURGY',
        material_type: 'RAW_MATERIAL',
        unit_cost: 850,
        unit_of_measure: 'KG',
        criticality: 'HIGH',
        lead_time_days: 14,
        safety_stock: 1200,
        minimum_order_qty: 500,
        primary_supplier_id: 'SUP-015',
        available_inventory: 3800,
        reserved_inventory: 2100,
        daily_consumption_rate: 160,
      },
      {
        material_id: 'MAT-3090',
        material_name: 'High-Density Optical Fiber Bus Coupler',
        material_category: 'OPTICS',
        material_type: 'RAW_MATERIAL',
        unit_cost: 310,
        unit_of_measure: 'UNIT',
        criticality: 'HIGH',
        lead_time_days: 18,
        safety_stock: 450,
        minimum_order_qty: 200,
        primary_supplier_id: 'SUP-089',
        available_inventory: 1620,
        reserved_inventory: 900,
        daily_consumption_rate: 80,
      },
      {
        material_id: 'MAT-4412',
        material_name: 'Ceramic Thermal Barrier Sub-Shield',
        material_category: 'THERMAL',
        material_type: 'RAW_MATERIAL',
        unit_cost: 190,
        unit_of_measure: 'UNIT',
        criticality: 'MEDIUM',
        lead_time_days: 10,
        safety_stock: 800,
        minimum_order_qty: 300,
        primary_supplier_id: 'SUP-007',
        available_inventory: 2400,
        reserved_inventory: 1100,
        daily_consumption_rate: 110,
      },
    ];
    materialData.forEach((m) => this.materials.set(m.material_id, m));

    // 3. PRODUCTS
    const productData: Product[] = [
      {
        product_id: 'PROD-5001',
        product_name: 'NexTurbine 9000 Industrial Co-Gen Generator',
        product_family: 'TURBINES',
        product_category: 'INDUSTRIAL_POWER',
        unit_price: 85000,
        standard_cost: 52700,
        margin: 0.38,
        production_time_hours: 48,
        criticality: 'MISSION_CRITICAL',
        active_flag: true,
      },
      {
        product_id: 'PROD-5004',
        product_name: 'NexDrive Precision Servo Controller Gen-IV',
        product_family: 'MECHATRONICS',
        product_category: 'ROBOTICS_AUTOMATION',
        unit_price: 34000,
        standard_cost: 19720,
        margin: 0.42,
        production_time_hours: 24,
        criticality: 'HIGH',
        active_flag: true,
      },
      {
        product_id: 'PROD-5012',
        product_name: 'RoboWeld Heavy Robotic Welder Core Unit',
        product_family: 'AUTOMATION',
        product_category: 'ADVANCED_MANUFACTURING',
        unit_price: 52000,
        standard_cost: 33800,
        margin: 0.35,
        production_time_hours: 32,
        criticality: 'HIGH',
        active_flag: true,
      },
    ];
    productData.forEach((p) => this.products.set(p.product_id, p));

    // 4. BOM (Multi-level Bill of Materials)
    this.boms = [
      // PROD-5001 -> COMP-204 and COMP-205
      {
        bom_id: 'BOM-001',
        product_id: 'PROD-5001',
        parent_item_id: 'PROD-5001',
        component_item_id: 'COMP-204',
        component_name: 'Optoelectronic MCU Sub-Assembly',
        component_type: 'COMPONENT',
        quantity_required: 2,
        scrap_factor: 0.02,
        effective_from: '2025-01-01',
      },
      {
        bom_id: 'BOM-002',
        product_id: 'PROD-5001',
        parent_item_id: 'PROD-5001',
        component_item_id: 'COMP-205',
        component_name: 'High-Voltage Power Inverter Unit',
        component_type: 'COMPONENT',
        quantity_required: 1,
        scrap_factor: 0.01,
        effective_from: '2025-01-01',
      },
      {
        bom_id: 'BOM-003',
        product_id: 'PROD-5001',
        parent_item_id: 'PROD-5001',
        component_item_id: 'MAT-2041',
        component_name: 'Aero-Grade Titanium Rods',
        component_type: 'RAW_MATERIAL',
        quantity_required: 12,
        scrap_factor: 0.04,
        effective_from: '2025-01-01',
      },
      // COMP-204 breakdown -> MAT-1007 and MAT-3090
      {
        bom_id: 'BOM-004',
        product_id: 'PROD-5001',
        parent_item_id: 'COMP-204',
        component_item_id: 'MAT-1007',
        component_name: 'Silicon Sensor Substrate',
        component_type: 'RAW_MATERIAL',
        quantity_required: 1,
        scrap_factor: 0.03,
        effective_from: '2025-01-01',
      },
      {
        bom_id: 'BOM-005',
        product_id: 'PROD-5001',
        parent_item_id: 'COMP-204',
        component_item_id: 'MAT-3090',
        component_name: 'Optical Fiber Bus Coupler',
        component_type: 'RAW_MATERIAL',
        quantity_required: 2,
        scrap_factor: 0.01,
        effective_from: '2025-01-01',
      },
      // COMP-205 breakdown -> MAT-1012 and MAT-4412
      {
        bom_id: 'BOM-006',
        product_id: 'PROD-5001',
        parent_item_id: 'COMP-205',
        component_item_id: 'MAT-1012',
        component_name: 'GaN Power Switching Die',
        component_type: 'RAW_MATERIAL',
        quantity_required: 2,
        scrap_factor: 0.02,
        effective_from: '2025-01-01',
      },
      {
        bom_id: 'BOM-007',
        product_id: 'PROD-5001',
        parent_item_id: 'COMP-205',
        component_item_id: 'MAT-4412',
        component_name: 'Ceramic Thermal Shield',
        component_type: 'RAW_MATERIAL',
        quantity_required: 3,
        scrap_factor: 0.01,
        effective_from: '2025-01-01',
      },
      // PROD-5004 -> COMP-204
      {
        bom_id: 'BOM-008',
        product_id: 'PROD-5004',
        parent_item_id: 'PROD-5004',
        component_item_id: 'COMP-204',
        component_name: 'Optoelectronic MCU Sub-Assembly',
        component_type: 'COMPONENT',
        quantity_required: 1,
        scrap_factor: 0.02,
        effective_from: '2025-01-01',
      },
      // PROD-5012 -> COMP-205
      {
        bom_id: 'BOM-009',
        product_id: 'PROD-5012',
        parent_item_id: 'PROD-5012',
        component_item_id: 'COMP-205',
        component_name: 'High-Voltage Power Inverter Unit',
        component_type: 'COMPONENT',
        quantity_required: 1,
        scrap_factor: 0.02,
        effective_from: '2025-01-01',
      },
    ];

    // 5. PLANTS
    const plantData: Plant[] = [
      {
        plant_id: 'PLANT-03',
        plant_name: 'Nexora Advanced Systems Plant — Stuttgart',
        country: 'Germany',
        region: 'EMEA',
        city: 'Stuttgart',
        latitude: 48.7758,
        longitude: 9.1829,
        plant_type: 'FINAL_ASSEMBLY_PRECISION',
        capacity_units: 12000,
        current_utilization: 0.88,
        operating_cost_per_hour: 450,
        active_flag: true,
      },
      {
        plant_id: 'PLANT-07',
        plant_name: 'Nexora Heavy Machinery Works — Detroit',
        country: 'USA',
        region: 'AMER',
        city: 'Detroit',
        latitude: 42.3314,
        longitude: -83.0458,
        plant_type: 'FINAL_ASSEMBLY_HEAVY',
        capacity_units: 8500,
        current_utilization: 0.84,
        operating_cost_per_hour: 520,
        active_flag: true,
      },
      {
        plant_id: 'PLANT-11',
        plant_name: 'Nexora Mechatronics Fab — Yokohama',
        country: 'Japan',
        region: 'APAC',
        city: 'Yokohama',
        latitude: 35.4437,
        longitude: 139.638,
        plant_type: 'SUB_ASSEMBLY_AND_ELECTRONICS',
        capacity_units: 15000,
        current_utilization: 0.91,
        operating_cost_per_hour: 410,
        active_flag: true,
      },
      {
        plant_id: 'PLANT-05',
        plant_name: 'Nexora Logistics & Buffer Hub — Munich',
        country: 'Germany',
        region: 'EMEA',
        city: 'Munich',
        latitude: 48.1351,
        longitude: 11.582,
        plant_type: 'BUFFER_AND_DISTRIBUTION',
        capacity_units: 20000,
        current_utilization: 0.62,
        operating_cost_per_hour: 280,
        active_flag: true,
      },
    ];
    plantData.forEach((p) => this.plants.set(p.plant_id, p));

    // 6. CUSTOMERS
    const customerData: Customer[] = [
      {
        customer_id: 'CUST-001',
        customer_name: 'Boeing Commercial Airplanes Group',
        industry: 'AEROSPACE',
        country: 'USA',
        region: 'AMER',
        city: 'Seattle',
        customer_tier: 'TIER_1',
        sla_days: 2,
        annual_revenue: 42000000,
      },
      {
        customer_id: 'CUST-002',
        customer_name: 'Siemens Energy AG',
        industry: 'POWER_UTILITIES',
        country: 'Germany',
        region: 'EMEA',
        city: 'Erlangen',
        customer_tier: 'TIER_1',
        sla_days: 3,
        annual_revenue: 31000000,
      },
      {
        customer_id: 'CUST-003',
        customer_name: 'Tesla Gigafactory Berlin-Brandenburg',
        industry: 'AUTOMOTIVE_EV',
        country: 'Germany',
        region: 'EMEA',
        city: 'Grünheide',
        customer_tier: 'TIER_1',
        sla_days: 2,
        annual_revenue: 38000000,
      },
      {
        customer_id: 'CUST-004',
        customer_name: 'GE Healthcare Bio-Medical',
        industry: 'MEDICAL_DEVICES',
        country: 'USA',
        region: 'AMER',
        city: 'Chicago',
        customer_tier: 'TIER_1',
        sla_days: 3,
        annual_revenue: 26000000,
      },
      {
        customer_id: 'CUST-005',
        customer_name: 'ABB Robotics & Motion',
        industry: 'ROBOTICS',
        country: 'Switzerland',
        region: 'EMEA',
        city: 'Zurich',
        customer_tier: 'TIER_2',
        sla_days: 5,
        annual_revenue: 19000000,
      },
      {
        customer_id: 'CUST-006',
        customer_name: 'Komatsu Heavy Industries',
        industry: 'HEAVY_EQUIPMENT',
        country: 'Japan',
        region: 'APAC',
        city: 'Tokyo',
        customer_tier: 'TIER_2',
        sla_days: 6,
        annual_revenue: 17500000,
      },
      {
        customer_id: 'CUST-007',
        customer_name: 'Emerson Electric Process Automation',
        industry: 'PROCESS_CONTROL',
        country: 'USA',
        region: 'AMER',
        city: 'St. Louis',
        customer_tier: 'TIER_3',
        sla_days: 8,
        annual_revenue: 11000000,
      },
    ];
    customerData.forEach((c) => this.customers.set(c.customer_id, c));

    // 7. CUSTOMER ORDERS (Representative 127 orders totaling $4,200,000 exposure for SUP-042 disruption)
    // We create realistic individual order records
    const sampleCustomerOrders: CustomerOrder[] = [
      {
        customer_order_id: 'ORD-900123',
        customer_id: 'CUST-001',
        customer_name: 'Boeing Commercial Airplanes Group',
        customer_tier: 'TIER_1',
        plant_id: 'PLANT-03',
        order_date: '2026-09-08',
        requested_date: '2026-09-24',
        promised_date: '2026-09-24',
        priority: 'EXPEDITE',
        status: 'AT_RISK',
        total_revenue: 680000, // 8 units of PROD-5001
      },
      {
        customer_order_id: 'ORD-900124',
        customer_id: 'CUST-002',
        customer_name: 'Siemens Energy AG',
        customer_tier: 'TIER_1',
        plant_id: 'PLANT-03',
        order_date: '2026-09-10',
        requested_date: '2026-09-26',
        promised_date: '2026-09-26',
        priority: 'HIGH',
        status: 'AT_RISK',
        total_revenue: 510000, // 6 units of PROD-5001
      },
      {
        customer_order_id: 'ORD-900125',
        customer_id: 'CUST-003',
        customer_name: 'Tesla Gigafactory Berlin',
        customer_tier: 'TIER_1',
        plant_id: 'PLANT-07',
        order_date: '2026-09-11',
        requested_date: '2026-09-25',
        promised_date: '2026-09-25',
        priority: 'EXPEDITE',
        status: 'AT_RISK',
        total_revenue: 714000, // 21 units of PROD-5004
      },
      {
        customer_order_id: 'ORD-900126',
        customer_id: 'CUST-004',
        customer_name: 'GE Healthcare Bio-Medical',
        customer_tier: 'TIER_1',
        plant_id: 'PLANT-11',
        order_date: '2026-09-12',
        requested_date: '2026-09-27',
        promised_date: '2026-09-27',
        priority: 'HIGH',
        status: 'AT_RISK',
        total_revenue: 520000, // 10 units of PROD-5012
      },
      {
        customer_order_id: 'ORD-900127',
        customer_id: 'CUST-005',
        customer_name: 'ABB Robotics & Motion',
        customer_tier: 'TIER_2',
        plant_id: 'PLANT-03',
        order_date: '2026-09-13',
        requested_date: '2026-09-28',
        promised_date: '2026-09-28',
        priority: 'NORMAL',
        status: 'AT_RISK',
        total_revenue: 408000, // 12 units of PROD-5004
      },
      {
        customer_order_id: 'ORD-900128',
        customer_id: 'CUST-006',
        customer_name: 'Komatsu Heavy Industries',
        customer_tier: 'TIER_2',
        plant_id: 'PLANT-07',
        order_date: '2026-09-14',
        requested_date: '2026-09-29',
        promised_date: '2026-09-29',
        priority: 'NORMAL',
        status: 'AT_RISK',
        total_revenue: 468000, // 9 units of PROD-5012
      },
      {
        customer_order_id: 'ORD-900129',
        customer_id: 'CUST-007',
        customer_name: 'Emerson Electric Automation',
        customer_tier: 'TIER_3',
        plant_id: 'PLANT-03',
        order_date: '2026-09-15',
        requested_date: '2026-10-02',
        promised_date: '2026-10-02',
        priority: 'NORMAL',
        status: 'AT_RISK',
        total_revenue: 900000, // Cumulative batched orders
      },
    ];
    sampleCustomerOrders.forEach((co) => this.customerOrders.set(co.customer_order_id, co));

    // 8. PURCHASE ORDERS
    const poData: PurchaseOrder[] = [
      {
        po_id: 'PO-12345',
        supplier_id: 'SUP-042',
        supplier_site_id: 'SITE-042-A',
        plant_id: 'PLANT-03',
        po_date: '2026-08-28',
        expected_date: '2026-09-20',
        status: 'DELAYED',
        priority: 'CRITICAL',
        total_value: 1260000,
      },
      {
        po_id: 'PO-12346',
        supplier_id: 'SUP-042',
        supplier_site_id: 'SITE-042-A',
        plant_id: 'PLANT-07',
        po_date: '2026-08-29',
        expected_date: '2026-09-22',
        status: 'DELAYED',
        priority: 'HIGH',
        total_value: 884000,
      },
      {
        po_id: 'PO-12347',
        supplier_id: 'SUP-042',
        supplier_site_id: 'SITE-042-B',
        plant_id: 'PLANT-11',
        po_date: '2026-08-30',
        expected_date: '2026-09-24',
        status: 'DELAYED',
        priority: 'HIGH',
        total_value: 680000,
      },
    ];
    poData.forEach((po) => this.purchaseOrders.set(po.po_id, po));

    // 9. CONTRACTS
    this.contracts.set('CTR-SUP042', {
      contract_id: 'CTR-SUP042',
      supplier_id: 'SUP-042',
      material_id: 'MAT-1007',
      contract_start: '2025-01-01',
      contract_end: '2027-12-31',
      agreed_price: 420,
      minimum_commitment: 5000,
      maximum_capacity: 12000,
      penalty_rate: 0.015, // 1.5% per week of unexcused delay
      expedite_available: true,
      alternate_source_allowed: true,
      notes: 'Clause 8.2: Air-freight expedite authorized up to 3,500 units with 48h notice. Dual-sourcing pre-approved if lead time breach exceeds 10 days.',
    });

    this.contracts.set('CTR-SUP118', {
      contract_id: 'CTR-SUP118',
      supplier_id: 'SUP-118',
      material_id: 'MAT-1007',
      contract_start: '2025-06-01',
      contract_end: '2027-06-01',
      agreed_price: 455, // +8% premium
      minimum_commitment: 1000,
      maximum_capacity: 6000,
      penalty_rate: 0.02,
      expedite_available: true,
      alternate_source_allowed: true,
      notes: 'Pre-qualified ISO-9001 alternate source. Rapid 3-day emergency dispatch enabled.',
    });

    // 10. PRIMARY CHAMPIONSHIP DISRUPTION & PREDEFINED SCENARIOS
    this.events.set('EVT-2026-042', {
      event_id: 'EVT-2026-042',
      event_type: 'SUPPLIER_DELAY',
      event_date: '2026-09-18T08:30:00Z',
      entity_type: 'SUPPLIER',
      entity_id: 'SUP-042',
      entity_name: 'Apex Micro-Foundry & Optics',
      severity: 'CRITICAL',
      duration_days: 14,
      probability: 0.95,
      description: 'Cleanroom HVAC chemical sensor contamination detected in Hsinchu Fab 3. Photolithography line halted for deep sanitization and requalification.',
      source: 'Automated Supplier EDI Telemetry (AS2/EDI 855)',
      status: 'INVESTIGATING',
      estimated_revenue_impact: 4200000,
      affected_materials: ['MAT-1007', 'MAT-1012'],
      affected_products: ['PROD-5001', 'PROD-5004', 'PROD-5012'],
      affected_plants: ['PLANT-03', 'PLANT-07', 'PLANT-11'],
    });

    // Add secondary disruptions for the registry
    this.events.set('EVT-2026-003', {
      event_id: 'EVT-2026-003',
      event_type: 'PORT_CLOSURE',
      event_date: '2026-09-17T14:15:00Z',
      entity_type: 'PORT',
      entity_id: 'PORT-ROTTERDAM',
      entity_name: 'Port of Rotterdam Terminal 4',
      severity: 'HIGH',
      duration_days: 6,
      probability: 0.88,
      description: 'Dockworkers union industrial action affecting container gantry cranes at Maasvlakte II.',
      source: 'MarineTraffic Satellite AIS Feed',
      status: 'MONITORING',
      estimated_revenue_impact: 1850000,
      affected_materials: ['MAT-2041'],
      affected_products: ['PROD-5001'],
      affected_plants: ['PLANT-03', 'PLANT-05'],
    });

    this.events.set('EVT-2026-008', {
      event_id: 'EVT-2026-008',
      event_type: 'WEATHER_DISRUPTION',
      event_date: '2026-09-16T19:00:00Z',
      entity_type: 'ROUTE',
      entity_id: 'ROUTE-PAC-04',
      entity_name: 'Trans-Pacific North Sea Route',
      severity: 'MEDIUM',
      duration_days: 4,
      probability: 0.92,
      description: 'Category 3 Super Typhoon Shanshan forcing container ships to divert south of Luzon Strait.',
      source: 'NOAA Ocean Weather Alert',
      status: 'RESOLVED',
      estimated_revenue_impact: 740000,
      affected_materials: ['MAT-3090'],
      affected_products: ['PROD-5004'],
      affected_plants: ['PLANT-11'],
    });

    // 11. SCENARIO LIBRARY (SCN-001 to SCN-010 + Compound Disruption)
    this.scenarios = [
      {
        scenario_id: 'SCN-001',
        code: 'CHAMPIONSHIP-042',
        name: 'Championship: SUP-042 Critical 14-Day Delivery Delay',
        description: 'Cleanroom contamination at Apex Micro-Foundry halting MAT-1007 & MAT-1012 wafer fabrication for 14 calendar days.',
        target_entity: 'SUP-042',
        duration_days: 14,
        severity: 'CRITICAL',
        parameters: { supplier_id: 'SUP-042', delay_days: 14 },
      },
      {
        scenario_id: 'SCN-002',
        code: 'SUPPLIER-FAIL',
        name: 'Catastrophic Supplier Insolvency (SUP-089)',
        description: 'Valencian Optics enters sudden restructuring and halts bus coupler deliveries for 30 days.',
        target_entity: 'SUP-089',
        duration_days: 30,
        severity: 'CRITICAL',
        parameters: { supplier_id: 'SUP-089', delay_days: 30 },
      },
      {
        scenario_id: 'SCN-003',
        code: 'PORT-SHUTDOWN',
        name: 'Rotterdam Port Congestion & Gantry Strike',
        description: 'Major transshipment bottleneck delaying European incoming materials by 8 days.',
        target_entity: 'PORT-ROTTERDAM',
        duration_days: 8,
        severity: 'HIGH',
        parameters: { delay_days: 8 },
      },
      {
        scenario_id: 'SCN-004',
        code: 'PLANT-OUTAGE',
        name: 'Detroit Heavy Works (PLANT-07) Substation Power Trip',
        description: 'Unplanned power loss requiring robotic welding recalibration and 5 days downtime.',
        target_entity: 'PLANT-07',
        duration_days: 5,
        severity: 'HIGH',
        parameters: { plant_id: 'PLANT-07', capacity_drop_pct: 100 },
      },
      {
        scenario_id: 'SCN-005',
        code: 'DEMAND-SURGE',
        name: 'Boeing & Siemens Tier-1 Demand Spike (+40%)',
        description: 'Unanticipated aerospace order surge draining factory safety buffers 2 weeks early.',
        target_entity: 'CUST-001',
        duration_days: 21,
        severity: 'HIGH',
        parameters: { demand_spike_pct: 40 },
      },
      {
        scenario_id: 'SCN-006',
        code: 'QUALITY-RECALL',
        name: 'Titanium Rod Alloy Purity Batch Defect (MAT-2041)',
        description: 'Non-destructive ultrasonic testing identifies micro-fissures in batch #TR-8812; 100% quarantine.',
        target_entity: 'MAT-2041',
        duration_days: 12,
        severity: 'CRITICAL',
        parameters: { delay_days: 12 },
      },
      {
        scenario_id: 'SCN-007',
        code: 'LOGISTICS-CHOKE',
        name: 'Suez Canal Navigational Grounding & Feeder Delay',
        description: 'Bulk carrier blockage expanding Asia-Europe maritime transit times by 10 days.',
        target_entity: 'CARRIER-MAERSK',
        duration_days: 10,
        severity: 'MEDIUM',
        parameters: { delay_days: 10 },
      },
      {
        scenario_id: 'SCN-008',
        code: 'RAW-SHORTAGE',
        name: 'Gallium & Germanium Export Licensing Quota Crunch',
        description: 'Geopolitical export restrictions driving +35% spot price spike and 20-day supply delay.',
        target_entity: 'MAT-1012',
        duration_days: 20,
        severity: 'CRITICAL',
        parameters: { delay_days: 20 },
      },
      {
        scenario_id: 'SCN-009',
        code: 'PRICE-SHOCK',
        name: 'Energy Tariff & Precious Metals Surcharge (+28%)',
        description: 'European utility price surge eroding unit margins across turbine components.',
        target_entity: 'PLANT-03',
        duration_days: 45,
        severity: 'LOW',
        parameters: { delay_days: 0 },
      },
      {
        scenario_id: 'SCN-010',
        code: 'COMPOUND-DISRUPT',
        name: 'Triple Compound: SUP-042 Delay + Boeing Surge + Plant-03 Strike',
        description: 'Simultaneous 14-day semiconductor delay combined with a 35% aerospace demand surge and 4-day labor slowdown in Stuttgart.',
        target_entity: 'COMPOUND',
        duration_days: 14,
        severity: 'CRITICAL',
        parameters: { supplier_id: 'SUP-042', delay_days: 14, demand_spike_pct: 35 },
      },
    ];
  }
}

export const digitalTwin = new DigitalTwinRepository();
